### PR TITLE
Cargo update to please audit

### PR DESCRIPTION
**Pull request by pradovic**

### CODE REVIEW

**Review by aphelionz — APPROVED** [review]
LGTM, no need for 24 hour wait as far as I can tell

**Review by koivunej — APPROVED** [review]
Looking good. ~Yeah I'll just merge this in to fix the build.~ Seems that the build is broken, lets see, something something about this yup-oauth. Lets not merge this yet then.

**Comment by koivunej** [comment]
Whoops, misclick, meant to refresh my own review status :)

**Comment by pradovic** [comment]
Solved by: https://github.com/interledger-rs/interledger-rs/pull/683

**Pull request closed without merging**
