### PR TITLE
docs: update HTTP docs for username changes

### PR DESCRIPTION
**Pull request by bstrie**

### CODE REVIEW

**Comment by bstrie** [comment]
@dora-gt Can you give me a good example of a `settlement_engine_url` to put in the docs here? We could also file an issue for that and merge this as-is.

**Comment by gakonst** [comment]
We've been using `http://localhost:3000` in our e2e tests, so you can use that @bstrie

**Comment by dora-gt** [comment]
@bstrie I made a PR: https://github.com/interledger-rs/interledger-rs/pull/331

**Comment by bstrie** [comment]
@dora-gt I've merged your PR, if you can approve this I'll merge it. :)

**Pull request merged**
