### PR TITLE
Add `Cargo.lock` to the repository

### PR DESCRIPTION
**Pull request by dora-gt**
- Remove `Cargo.lock` from `.gitignore`.
- Add `Cargo.lock` to the repository.
- This would make caching work more appropriately.

Ref:
- [Cargo.toml vs Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)
- [Why do binaries have `Cargo.lock` in version control, but not libraries?](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)

### CODE REVIEW

**Comment by dora-gt** [comment]
oops... I'm not sure what's happening, I'll check later.

```
#!/bin/bash -eo pipefail
LD_PRELOAD=/usr/lib/libcurl.so.3 cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 41 security advisories (from /home/circleci/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (352 crate dependencies)
error: Vulnerable crates found!

ID:	 RUSTSEC-2019-0013
Crate:	 spin
Version: 0.5.1
Date:	 2019-08-27
URL:	 https://github.com/mvdnes/spin-rs/issues/65
Title:	 Wrong memory orderings in RwLock potentially violates mutual exclusion
Solution: upgrade to: >= 0.5.2

error: 1 vulnerability found!
Exited with code 1
```

**Comment by dora-gt** [comment]
Updated spin from `v0.5.1` to `v0.5.2`. Although Commit Message Lint says that the message is not correct, it would be fixed with #289. I'm merging this.

**Comment by bstrie** [comment]
@dora-gt Isn't it 04:00 there? Go to sleep! :P

**Comment by dora-gt** [comment]
Haha, I just want to fix a bug of #305. Thanks Ben😂

**Pull request merged**
